using Microsoft.Extensions.Options;
using Moq;
using Moq.Protected;
using Newtonsoft.Json;
using zTools.Domain.Services;
using zTools.DTO.InVideo;
using zTools.DTO.Settings;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Xunit;

namespace zTools.Tests.Domain.Services
{
    public class InVideoServiceTests
    {
        private readonly Mock<IOptions<InVideoSetting>> _mockInVideoSettings;
        private readonly InVideoSetting _inVideoSetting;
        private readonly HttpClient _httpClient;

        public InVideoServiceTests()
        {
            _inVideoSetting = new InVideoSetting
            {
                ApiUrl = "https://pro-api.invideo.io/v1/generate-video",
                ApiKey = "test-api-key-12345"
            };

            _mockInVideoSettings = new Mock<IOptions<InVideoSetting>>();
            _mockInVideoSettings.Setup(x => x.Value).Returns(_inVideoSetting);

            _httpClient = new HttpClient();
        }

        private static InVideoResponse CreateTestResponse()
        {
            return new InVideoResponse
            {
                VideoUrl = "https://invideo.io/videos/test-video-123",
                Title = "Test Video",
                Description = "A test video generated by InVideo AI"
            };
        }

        [Fact]
        public void Constructor_WithValidSettings_InitializesSuccessfully()
        {
            var service = new InVideoService(_httpClient, _mockInVideoSettings.Object);
            Assert.NotNull(service);
        }

        [Fact]
        public void Constructor_WithNullHttpClient_ThrowsArgumentNullException()
        {
            Assert.Throws<System.ArgumentNullException>(() => new InVideoService(null, _mockInVideoSettings.Object));
        }

        [Fact]
        public void Constructor_WithNullSettings_ThrowsArgumentNullException()
        {
            Assert.Throws<System.ArgumentNullException>(() => new InVideoService(_httpClient, null));
        }

        [Fact]
        public async Task GenerateVideoAsync_WithPrompt_ReturnsResponse()
        {
            // Arrange
            var mockHandler = new Mock<HttpMessageHandler>();
            var expectedResponse = CreateTestResponse();
            var responseJson = JsonConvert.SerializeObject(expectedResponse);

            mockHandler.Protected()
                .Setup<Task<HttpResponseMessage>>(
                    "SendAsync",
                    ItExpr.IsAny<HttpRequestMessage>(),
                    ItExpr.IsAny<CancellationToken>())
                .ReturnsAsync(new HttpResponseMessage
                {
                    StatusCode = HttpStatusCode.OK,
                    Content = new StringContent(responseJson)
                });

            var httpClient = new HttpClient(mockHandler.Object);
            var service = new InVideoService(httpClient, _mockInVideoSettings.Object);

            // Act
            var result = await service.GenerateVideoAsync("Create a video about cats");

            // Assert
            Assert.NotNull(result);
            Assert.Equal(expectedResponse.VideoUrl, result.VideoUrl);
            Assert.Equal(expectedResponse.Title, result.Title);
            Assert.Equal(expectedResponse.Description, result.Description);
        }

        [Fact]
        public async Task GenerateVideoAsync_WithRequest_ReturnsResponse()
        {
            // Arrange
            var mockHandler = new Mock<HttpMessageHandler>();
            var expectedResponse = CreateTestResponse();
            var responseJson = JsonConvert.SerializeObject(expectedResponse);

            mockHandler.Protected()
                .Setup<Task<HttpResponseMessage>>(
                    "SendAsync",
                    ItExpr.IsAny<HttpRequestMessage>(),
                    ItExpr.IsAny<CancellationToken>())
                .ReturnsAsync(new HttpResponseMessage
                {
                    StatusCode = HttpStatusCode.OK,
                    Content = new StringContent(responseJson)
                });

            var httpClient = new HttpClient(mockHandler.Object);
            var service = new InVideoService(httpClient, _mockInVideoSettings.Object);

            var request = new InVideoRequest
            {
                Prompt = "Create a video about technology",
                Duration = 5.0,
                Platform = "youtube_shorts",
                Voice = "male",
                Accent = "american"
            };

            // Act
            var result = await service.GenerateVideoAsync(request);

            // Assert
            Assert.NotNull(result);
            Assert.Equal(expectedResponse.VideoUrl, result.VideoUrl);
        }

        [Fact]
        public async Task GenerateVideoAsync_WhenApiReturnsErrorWithMessage_ThrowsInvalidOperationException()
        {
            // Arrange
            var mockHandler = new Mock<HttpMessageHandler>();
            var errorResponse = new InVideoErrorResponse
            {
                Error = new InVideoError
                {
                    Message = "Invalid API key",
                    Code = "invalid_api_key"
                }
            };
            var errorJson = JsonConvert.SerializeObject(errorResponse);

            mockHandler.Protected()
                .Setup<Task<HttpResponseMessage>>(
                    "SendAsync",
                    ItExpr.IsAny<HttpRequestMessage>(),
                    ItExpr.IsAny<CancellationToken>())
                .ReturnsAsync(new HttpResponseMessage
                {
                    StatusCode = HttpStatusCode.Unauthorized,
                    Content = new StringContent(errorJson)
                });

            var httpClient = new HttpClient(mockHandler.Object);
            var service = new InVideoService(httpClient, _mockInVideoSettings.Object);

            // Act & Assert
            var exception = await Assert.ThrowsAsync<System.InvalidOperationException>(
                async () => await service.GenerateVideoAsync("test"));

            Assert.Equal("Invalid API key", exception.Message);
        }

        [Fact]
        public async Task GenerateVideoAsync_WhenApiReturnsErrorWithoutMessage_ThrowsUnknownError()
        {
            // Arrange
            var mockHandler = new Mock<HttpMessageHandler>();
            var errorResponse = new InVideoErrorResponse
            {
                Error = new InVideoError { Message = null }
            };
            var errorJson = JsonConvert.SerializeObject(errorResponse);

            mockHandler.Protected()
                .Setup<Task<HttpResponseMessage>>(
                    "SendAsync",
                    ItExpr.IsAny<HttpRequestMessage>(),
                    ItExpr.IsAny<CancellationToken>())
                .ReturnsAsync(new HttpResponseMessage
                {
                    StatusCode = HttpStatusCode.BadRequest,
                    Content = new StringContent(errorJson)
                });

            var httpClient = new HttpClient(mockHandler.Object);
            var service = new InVideoService(httpClient, _mockInVideoSettings.Object);

            var request = new InVideoRequest { Prompt = "test" };

            // Act & Assert
            var exception = await Assert.ThrowsAsync<System.InvalidOperationException>(
                async () => await service.GenerateVideoAsync(request));

            Assert.Equal("Unknown error", exception.Message);
        }

        [Fact]
        public async Task GenerateVideoAsync_WhenApiReturnsNullError_ThrowsUnknownError()
        {
            // Arrange
            var mockHandler = new Mock<HttpMessageHandler>();

            mockHandler.Protected()
                .Setup<Task<HttpResponseMessage>>(
                    "SendAsync",
                    ItExpr.IsAny<HttpRequestMessage>(),
                    ItExpr.IsAny<CancellationToken>())
                .ReturnsAsync(new HttpResponseMessage
                {
                    StatusCode = HttpStatusCode.InternalServerError,
                    Content = new StringContent("null")
                });

            var httpClient = new HttpClient(mockHandler.Object);
            var service = new InVideoService(httpClient, _mockInVideoSettings.Object);

            // Act & Assert
            var exception = await Assert.ThrowsAsync<System.InvalidOperationException>(
                async () => await service.GenerateVideoAsync("test"));

            Assert.Equal("Unknown error", exception.Message);
        }

        [Theory]
        [InlineData("Create a video about cats")]
        [InlineData("Make an ad for my product")]
        [InlineData("Generate an educational video about space")]
        public async Task GenerateVideoAsync_WithVariousPrompts_ReturnsResponse(string prompt)
        {
            // Arrange
            var mockHandler = new Mock<HttpMessageHandler>();
            var expectedResponse = CreateTestResponse();
            var responseJson = JsonConvert.SerializeObject(expectedResponse);

            mockHandler.Protected()
                .Setup<Task<HttpResponseMessage>>(
                    "SendAsync",
                    ItExpr.IsAny<HttpRequestMessage>(),
                    ItExpr.IsAny<CancellationToken>())
                .ReturnsAsync(new HttpResponseMessage
                {
                    StatusCode = HttpStatusCode.OK,
                    Content = new StringContent(responseJson)
                });

            var httpClient = new HttpClient(mockHandler.Object);
            var service = new InVideoService(httpClient, _mockInVideoSettings.Object);

            // Act
            var result = await service.GenerateVideoAsync(prompt);

            // Assert
            Assert.NotNull(result);
            Assert.Equal(expectedResponse.VideoUrl, result.VideoUrl);
        }

        [Fact]
        public void InVideoSetting_ConfigurationValues_AreAccessible()
        {
            Assert.Equal("https://pro-api.invideo.io/v1/generate-video", _inVideoSetting.ApiUrl);
            Assert.Equal("test-api-key-12345", _inVideoSetting.ApiKey);
        }

        [Fact]
        public void InVideoRequest_Serialization_ProducesCorrectJson()
        {
            // Arrange
            var request = new InVideoRequest
            {
                Prompt = "Test video",
                Duration = 10.0,
                Platform = "tiktok",
                Voice = "female",
                Accent = "british"
            };

            // Act
            var json = JsonConvert.SerializeObject(request);
            var deserialized = JsonConvert.DeserializeObject<InVideoRequest>(json);

            // Assert
            Assert.NotNull(deserialized);
            Assert.Equal(request.Prompt, deserialized.Prompt);
            Assert.Equal(request.Duration, deserialized.Duration);
            Assert.Equal(request.Platform, deserialized.Platform);
            Assert.Equal(request.Voice, deserialized.Voice);
            Assert.Equal(request.Accent, deserialized.Accent);
        }

        [Fact]
        public void InVideoResponse_Deserialization_ParsesCorrectly()
        {
            // Arrange
            var responseJson = @"{
                ""video_url"": ""https://invideo.io/videos/abc123"",
                ""title"": ""My Video"",
                ""description"": ""A great video""
            }";

            // Act
            var response = JsonConvert.DeserializeObject<InVideoResponse>(responseJson);

            // Assert
            Assert.NotNull(response);
            Assert.Equal("https://invideo.io/videos/abc123", response.VideoUrl);
            Assert.Equal("My Video", response.Title);
            Assert.Equal("A great video", response.Description);
        }

        [Fact]
        public void InVideoErrorResponse_Deserialization_ParsesCorrectly()
        {
            // Arrange
            var errorJson = @"{
                ""error"": {
                    ""message"": ""Rate limit exceeded"",
                    ""code"": ""rate_limit""
                }
            }";

            // Act
            var errorResponse = JsonConvert.DeserializeObject<InVideoErrorResponse>(errorJson);

            // Assert
            Assert.NotNull(errorResponse);
            Assert.NotNull(errorResponse.Error);
            Assert.Equal("Rate limit exceeded", errorResponse.Error.Message);
            Assert.Equal("rate_limit", errorResponse.Error.Code);
        }
    }
}
